### ISSUE TITLE
Staged build gives node error

### ISSUE THREAD

**Issue by ChuckIrvine** [DenysVuika/medium-angular-docker#39]
I am working from your tutorial at https://denys.dev/2018-03-02/your-angular-apps-as-docker-containers/. The tutorial is excellent, but when I get to the staged image build, I get a node related error. When I run:
```
docker image build -t my-angular-app .
```
I get this error:
```
> angular-docker@0.0.0 build /usr/src/app
> ng build --prod

You are running version v10.4.1 of Node.js, which is not supported by Angular CLI 8.0+.
The official Node.js version that is supported is 10.9 or greater.

Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! angular-docker@0.0.0 build: `ng build --prod`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the angular-docker@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-09T01_05_45_413Z-debug.log
The command '/bin/sh -c npm ci && npm run build' returned a non-zero code: 3
```

I'm running your code that I just cloned form GitHub.

I'm not familiar enough with what docker is doing with node to understand what the problem is.

Any ideas?

Thanks!!

**Comment by DenysVuika** [comment]
According to the error details that Angular raises

```
You are running version v10.4.1 of Node.js, which is not supported by Angular CLI 8.0+.
The official Node.js version that is supported is 10.9 or greater.
```

You need to update your node.js

**Comment by ChuckIrvine** [comment]
When I check my version of node it get:

````
$ node -v
v10.16.0
````

So, it seems that locally I am running 10.16.0. Any idea on how I would be picking up version 10.4.1?

Thanks!

**Comment by ChuckIrvine** [comment]
Another thought... I'm not smart enough about docker yet, but is it possible that I'm picking up node from the "node:10.4-alpine" image?

**Comment by ChuckIrvine** [comment]
It seems that version 10.4.1 is coming from the version of node in "node:10.4-alpine". I created a test Dockerfile with contents:

```
$ cat Dockerfile 
FROM node:10.4-alpine

RUN node -v
```

When I build that image I get:

```
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM node:10.4-alpine
 ---> 1a27bb341f3f
Step 2/2 : RUN node -v
 ---> Using cache
 ---> c9364f729bc4
Successfully built c9364f729bc4
```

**Comment by DenysVuika** [comment]
I can reproduce this issue now, working on a fix

**Comment by ChuckIrvine** [comment]
Thanks! Your tutorial is excellent, by the way. I'm learning a lot.

**Comment by DenysVuika** [comment]
Updated the Dockerfile, can you try again to see if that fixes the issue for you? I tried locally and should be fine now.

**Comment by ChuckIrvine** [comment]
Yes, the build worked fine. I did see that someone else that read your tutorial seemed to have the same problem. In her response, she just mentioned the error but didn't provide enough context:

```
The command '/bin/sh -c npm ci && npm run build' returned a non-zero code: 3
```

Thanks
